substitutions:
  device: 
    name:                   i2c-screen
    comment:                "QuinLED Dig-Uno"
    version:                "0.1-rc1"
  system:
    reboot_timeout:         60min
    log_level:              DEBUG
  sntp:
    server:                 192.168.3.1
  web_server:
    include_internal:       'true'
    local:                  'false'
  light:
    digital:
      num_leds:             96
      transition_length:    1s

esphome:
  name: ${device.name}
  friendly_name: ${device.name}
  comment: ${device.comment}
  project: 
    name: timota.${device.name}
    version: ${device.version}

  on_boot:
    priority: -100
    then:
      - display.page.show: page_boot
      - component.update: oled
      - delay: 5s
      - display.page.show: page_env
      - component.update: oled

  # devices: 
  #   - id: light_rgbww
  #     name: ${device.name}-rgbww
  #   - id: light_digital
  #     name: ${device.name}-dig

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${system.reboot_timeout}
  # used to prevent flicking during effects
  power_save_mode: none
  min_auth_mode: WPA2

  ap:
    ssid: ${device.name}
    password: !secret failover_password

api:
  id: api_server
  reboot_timeout: ${system.reboot_timeout}
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: ${system.log_level}

web_server:
  include_internal: true

i2c:
  id: bus_a
  sda: GPIO2
  scl: GPIO32
  # frequency: 100kHz

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

# switch:
#   - platform: gpio
#     name: "Digital LED Power Relay"
#     id: dig_power
#     pin:
#       mcp23xxx: mcp23017_hub
#       number: 10
#     entity_category: config
#     # disabled_by_default: True

binary_sensor:
  - platform: gpio
    name: "MCP23017 Pin A1"
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 1
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: "MCP23017 Pin A5"
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 5
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: true

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

  - platform: safe_mode
    internal: false
    name: Safe mode
    entity_category: config
    disabled_by_default: True

power_supply:
  - id: dig_power
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
    keep_on_time: 1s

font:
  - file: "gfonts://Roboto+Mono"
    id: mono_8
    size: 8
    glyphs: "0123456789.-topbm"
  - file: "gfonts://Roboto+Mono"
    id: mono_22
    size: 22
    glyphs: "0123456789.-°"
  - file: "assets/materialdesignicons-webfont.ttf"
    id: mdi_56
    size: 56
    glyphs:
      - "\U000F0F55"
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
    glyphs: "Rack Conteldr"

image:
  - file: "assets/ha_logo_48px.xbm"
    id: ha_logo
    type: BINARY

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 128x64"
    update_interval: 1s
    pages:
      - id: page_boot
        lambda: |-
          it.fill(Color::BLACK);
          it.image(40, 0, id(ha_logo));
          it.printf(64, 50, id(roboto_12), TextAlign::CENTER_HORIZONTAL, "Rack Controller");
      - id: page_env
        lambda: |-
          it.fill(Color::BLACK);
          it.printf(-4, 2, id(mdi_56), "\U000F0F55");

          it.printf(121, -4, id(mono_8), TextAlign::TOP_RIGHT, "top");
          if (isnan(id(sht40_temp).state)) {
            it.printf(65, 3, id(mono_22), "---.-");
          } else {
            it.printf(65, 3, id(mono_22), "%.1f", id(sht40_temp).state);
          }
          it.printf(111, 3, id(mono_22), "°");

          it.printf(121, 32, id(mono_8), TextAlign::TOP_RIGHT, "bottom");
          if (isnan(id(dig_temperature).state)) {
            it.printf(65, 39, id(mono_22), "---.-");
          } else {
            it.printf(65, 39, id(mono_22), "%.1f", id(dig_temperature).state);
          }
          it.printf(111, 39, id(mono_22), "°");

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: sht4x
    address: 0x44
    update_interval: 20s
    temperature:
      id: sht40_temp
      name: "Rack Top Temp"
      device_class: temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    humidity:
      id: sht40_humidity
      name: "Rack Top Humidity"
      device_class: humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1

  - platform: dallas_temp
    id: dig_temperature
    name: "Temperature Dig Uno"
    unit_of_measurement: "°C"
    device_class: temperature
    update_interval: 30s
    address: 0xba000005a107ea28

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 2s


light:
    
  - platform: esp32_rmt_led_strip
    id: light_dig
    name: Wall
    rgb_order: GRB
    pin: GPIO16
    num_leds: 19
    chipset: SK6812
    is_rgbw: True
    # is_wrgb: True
    # max_refresh_rate: 30ms
    use_psram: False
    restore_mode: ALWAYS_OFF
    default_transition_length: ${light.digital.transition_length}
    power_supply: dig_power
    # on_turn_on: 
    #   then:
    #     - switch.turn_on: dig_power
    # on_turn_off:
    #   then:
    #     - switch.turn_off: dig_power
    effects:
      - random:          
          name: "Slow Random Effect"
          transition_length: 60s
          update_interval: 60s
      - random:
          name: "Medium Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 10s
          update_interval: 10s
      - random:
          name: "Very Fast Random Effect"
          transition_length: 1s
          update_interval: 1s
      - addressable_random_twinkle:
          name: "Random Twinkle Effect"
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_flicker:
          name: "Flicker Effect"
          update_interval: 16ms
          intensity: 5%
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: "Wipe_In"
          add_led_interval: 40ms
      - addressable_color_wipe:
          name: "Wipe_Out"
          add_led_interval: 40ms   
          reverse: True
      - addressable_color_wipe:
          name: "My Wipe"
          colors:
            - red: 50%
              green: 70%
              blue: 80%
              num_leds: 1
              gradient: true
          add_led_interval: 40ms
      - addressable_twinkle:
      - addressable_fireworks:
