substitutions:
  device: 
    name:                   i2c-screen
    comment:                "QuinLED Dig-Uno"
    version:                "0.1-rc1"
  system:
    reboot_timeout:         60min
    log_level:              DEBUG
  sntp:
    server:                 192.168.3.1
  web_server:
    include_internal:       'true'
    local:                  'false'
  light:
    digital:
      num_leds:             96
      transition_length:    1s

esphome:
  name: ${device.name}
  friendly_name: ${device.name}
  comment: ${device.comment}
  project: 
    name: timota.${device.name}
    version: ${device.version}

  on_boot:
    priority: -100
    then:
      - display.page.show: page_boot
      - component.update: oled
      - delay: 5s
      - display.page.show: page_env
      - component.update: oled

  # devices: 
  #   - id: light_rgbww
  #     name: ${device.name}-rgbww
  #   - id: light_digital
  #     name: ${device.name}-dig

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${system.reboot_timeout}
  # used to prevent flicking during effects
  power_save_mode: none
  min_auth_mode: WPA2

  ap:
    ssid: ${device.name}
    password: !secret failover_password

api:
  id: api_server
  reboot_timeout: ${system.reboot_timeout}
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: ${system.log_level}

web_server:
  include_internal: true

i2c:
  id: bus_a
  sda: GPIO2
  scl: GPIO32
  # frequency: 100kHz

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

# switch:
#   - platform: gpio
#     name: "Digital LED Power Relay"
#     id: dig_power
#     pin:
#       mcp23xxx: mcp23017_hub
#       number: 10
#     entity_category: config
#     # disabled_by_default: True

binary_sensor:
  - platform: gpio
    name: "Red"
    id: button_red
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 1
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then:
          - lambda: |-
              const bool is_on = id(light_dig).current_values.is_on();
              if (is_on) {
                id(strip_manual_override) = false;
                auto call = id(light_dig).turn_off();
                call.perform();
              } else {
                id(strip_manual_override) = true;
                auto call = id(light_dig).turn_on();
                call.perform();
              }
          - script.execute: auto_off_timer
  - platform: gpio
    name: "Yellow"
    id: button_yellow
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 5
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then:
          - lambda: |-
              static const float colors[][4] = {
                {1.0f, 0.0f, 0.0f, 0.0f},  // red
                {0.0f, 1.0f, 0.0f, 0.0f},  // green
                {0.0f, 0.0f, 1.0f, 0.0f},  // blue
                {1.0f, 1.0f, 1.0f, 0.0f},  // rgb white
                {0.0f, 0.0f, 0.0f, 1.0f},  // pure white (W only)
                {1.0f, 1.0f, 1.0f, 0.5f},  // composed white (RGB+W)
                {1.0f, 0.5f, 0.0f, 0.0f},  // orange
                {0.6f, 0.0f, 1.0f, 0.0f},  // purple
                {0.0f, 1.0f, 1.0f, 0.0f},  // cyan
              };
              const int count = sizeof(colors) / sizeof(colors[0]);
              id(color_index) = (id(color_index) + 1) % count;
              auto call = id(light_dig).turn_on();
              call.set_rgbw(colors[id(color_index)][0],
                            colors[id(color_index)][1],
                            colors[id(color_index)][2],
                            colors[id(color_index)][3]);
              call.perform();

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

  - platform: safe_mode
    internal: false
    name: Safe mode
    entity_category: config
    disabled_by_default: True

power_supply:
  - id: dig_power
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
    keep_on_time: 1s

font:
  - file: "gfonts://Roboto+Mono"
    id: mono_8
    size: 8
    glyphs: "0123456789.-topbm"
  - file: "gfonts://Roboto+Mono"
    id: mono_22
    size: 22
    glyphs: "0123456789.-°"
  - file: "assets/materialdesignicons-webfont.ttf"
    id: mdi_56
    size: 56
    glyphs:
      - "\U000F0F55"
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
    glyphs: "Rack Conteldr"

image:
  - file: "assets/ha_logo_48px.xbm"
    id: ha_logo
    type: BINARY

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 128x64"
    update_interval: 30s
    pages:
      - id: page_boot
        lambda: |-
          it.fill(Color::BLACK);
          it.image(40, 0, id(ha_logo));
          it.printf(64, 50, id(roboto_12), TextAlign::CENTER_HORIZONTAL, "Rack Controller");
      - id: page_env
        lambda: |-
          it.fill(Color::BLACK);
          it.printf(-4, 2, id(mdi_56), "\U000F0F55");

          it.printf(121, -4, id(mono_8), TextAlign::TOP_RIGHT, "top");
          if (isnan(id(sht40_temp).state)) {
            it.printf(65, 3, id(mono_22), "---.-");
          } else {
            it.printf(65, 3, id(mono_22), "%.1f", id(sht40_temp).state);
          }
          it.printf(115, 3, id(mono_22), "°");

          it.printf(121, 32, id(mono_8), TextAlign::TOP_RIGHT, "bottom");
          if (isnan(id(dig_temperature).state)) {
            it.printf(65, 39, id(mono_22), "---.-");
          } else {
            it.printf(65, 39, id(mono_22), "%.1f", id(dig_temperature).state);
          }
          it.printf(115, 39, id(mono_22), "°");

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: sht4x
    address: 0x44
    update_interval: 20s
    temperature:
      id: sht40_temp
      name: "Rack Top Temp"
      device_class: temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      on_value:
        then:
          - if:
              condition:
                lambda: 'return id(display_is_on);'
              then:
                - component.update: oled
    humidity:
      id: sht40_humidity
      name: "Rack Top Humidity"
      device_class: humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1

  - platform: dallas_temp
    id: dig_temperature
    name: "Temperature Dig Uno"
    unit_of_measurement: "°C"
    device_class: temperature
    update_interval: 30s
    address: 0xba000005a107ea28
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(display_is_on);'
            then:
              - component.update: oled

  - platform: bh1750
    id: bh1750_illuminance
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 1s
    on_value:
      then:
        - script.execute: update_lux_actions

number:
  - platform: template
    id: lux_off_threshold
    name: "Display Lux Off Threshold"
    unit_of_measurement: "lx"
    min_value: 0
    max_value: 2000
    step: 1
    mode: box
    restore_value: true
    initial_value: 2
    optimistic: true

  - platform: template
    id: lux_on_threshold
    name: "Display Lux On Threshold"
    unit_of_measurement: "lx"
    min_value: 0
    max_value: 2000
    step: 1
    mode: box
    restore_value: true
    initial_value: 3
    optimistic: true

  - platform: template
    id: strip_transition_seconds
    name: "Strip Transition (sec)"
    unit_of_measurement: "s"
    min_value: 0
    max_value: 30
    step: 0.5
    mode: box
    restore_value: true
    initial_value: 1
    optimistic: true

  - platform: template
    id: auto_off_minutes
    name: "Auto Off Timeout (min)"
    unit_of_measurement: "min"
    min_value: 0
    max_value: 240
    step: 1
    mode: box
    restore_value: true
    initial_value: 30
    optimistic: true

switch:
  - platform: template
    id: illuminance_controls_strip
    name: "Illuminance Controls Strip"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true

script:
  - id: update_lux_actions
    mode: restart
    then:
      - lambda: |-
          const float lux = id(bh1750_illuminance).state;
          const float off_th = id(lux_off_threshold).state;
          const float on_th = id(lux_on_threshold).state;

          if (isnan(lux) || isnan(off_th) || isnan(on_th)) return;

          if (lux <= off_th) {
            id(apply_display).execute(false);
            id(apply_strip).execute(false);
          } else if (lux >= on_th) {
            id(strip_manual_override) = false;
            id(apply_display).execute(true);
            id(apply_strip).execute(true);
          } else {
            return;
          }

  - id: apply_strip
    mode: restart
    parameters:
      target_on: bool
    then:
      - if:
          condition:
            lambda: 'return id(illuminance_controls_strip).state;'
          then:
            - if:
                condition:
                  lambda: 'return !target_on && id(strip_manual_override);'
                then:
                  - lambda: |-
                      return;
                else:
                  - if:
                      condition:
                        lambda: 'return target_on;'
                      then:
                        - light.turn_on:
                            id: light_dig
                            transition_length: !lambda 'return (uint32_t) (id(strip_transition_seconds).state * 1000);'
                        - script.execute: auto_off_timer
                      else:
                        - light.turn_off:
                            id: light_dig
                            transition_length: !lambda 'return (uint32_t) (id(strip_transition_seconds).state * 1000);'

  - id: apply_display
    mode: restart
    parameters:
      target_on: bool
    then:
      - if:
          condition:
            lambda: 'return target_on;'
          then:
            - script.execute: fade_in
            - script.execute: auto_off_timer
          else:
            - script.execute: fade_out

  - id: auto_off_timer
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(auto_off_minutes).state > 0;'
          then:
            - delay: !lambda 'return (uint32_t) (id(auto_off_minutes).state * 60000);'
            - script.execute: force_all_off

  - id: force_all_off
    mode: restart
    then:
      - lambda: |-
          id(strip_manual_override) = false;
      - script.execute:
          id: apply_display
          target_on: false
      - script.execute:
          id: apply_strip
          target_on: false

  - id: fade_out
    mode: restart
    then:
      - lambda: |-
          id(display_is_on) = false;
      - while:
          condition:
            lambda: 'return id(display_contrast) > 0;'
          then:
            - lambda: |-
                id(display_contrast) = max(0, id(display_contrast) - 60);
                id(oled).set_contrast(id(display_contrast));
            - component.update: oled
            - delay: 10ms
      - lambda: |-
          id(oled).turn_off();

  - id: fade_in
    mode: restart
    then:
      - lambda: |-
          id(oled).turn_on();
          id(display_is_on) = true;
      - while:
          condition:
            lambda: 'return id(display_contrast) < 255;'
          then:
            - lambda: |-
                id(display_contrast) = min(255, id(display_contrast) + 60);
                id(oled).set_contrast(id(display_contrast));
            - component.update: oled
            - delay: 10ms
      - component.update: oled

globals:
  - id: display_contrast
    type: int
    restore_value: no
    initial_value: '255'
  - id: display_is_on
    type: bool
    restore_value: no
    initial_value: 'true'
  - id: color_index
    type: int
    restore_value: no
    initial_value: '-1'
  - id: strip_manual_override
    type: bool
    restore_value: no
    initial_value: 'false'


light:
    
  - platform: esp32_rmt_led_strip
    id: light_dig
    name: Wall
    rgb_order: GRB
    pin: GPIO16
    num_leds: 19
    chipset: SK6812
    is_rgbw: True
    # is_wrgb: True
    # max_refresh_rate: 30ms
    use_psram: False
    restore_mode: ALWAYS_OFF
    default_transition_length: ${light.digital.transition_length}
    power_supply: dig_power
    # on_turn_on: 
    #   then:
    #     - switch.turn_on: dig_power
    # on_turn_off:
    #   then:
    #     - switch.turn_off: dig_power
    effects:
      - random:          
          name: "Slow Random Effect"
          transition_length: 60s
          update_interval: 60s
      - random:
          name: "Medium Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 10s
          update_interval: 10s
      - random:
          name: "Very Fast Random Effect"
          transition_length: 1s
          update_interval: 1s
      - addressable_random_twinkle:
          name: "Random Twinkle Effect"
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_flicker:
          name: "Flicker Effect"
          update_interval: 16ms
          intensity: 5%
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: "Wipe_In"
          add_led_interval: 40ms
      - addressable_color_wipe:
          name: "Wipe_Out"
          add_led_interval: 40ms   
          reverse: True
      - addressable_color_wipe:
          name: "My Wipe"
          colors:
            - red: 50%
              green: 70%
              blue: 80%
              num_leds: 1
              gradient: true
          add_led_interval: 40ms
      - addressable_twinkle:
      - addressable_fireworks:
