substitutions:
  device_name: i2c-screen
  system_log_level: NONE

packages:
  rack_ctrl:
    url: https://github.com/timota/esphome-devices
    ref: main
    refresh: 1min
    files:
      - rack-ctrl/package.yaml