substitutions:
  device_name: stairs-ctrl
  device_friendly_name: stairs-ctrl-strip
  device_comment: "Stairs controller"
  device_version: "0.1-rc1"

  system_reboot_timeout: 60min
  system_log_level: INFO
  system_api_key: "00000000000000000000000000000000"
  system_ota_password: "changeme"
  system_timezone: UTC

  sntp_server: time1.google.com
  web_include_internal: "false"
  web_local: "false"

  light_num_leds: "244"
  light_transition_length: 1.5s
  light_brightness_r: "1"
  light_brightness_g: "1"
  light_brightness_b: "1"
  light_led_map: '{{0,1,2,3,4,5},{10,9,8,7,6},{11,12,13,14},{20,19,18,17,16,15}}'

  ethernet_mdc_pin: GPIO23
  ethernet_mdio_pin: GPIO18
  ethernet_clk_pin: GPIO17
  ethernet_phy_addr: "0"
  ethernet_power_pin: GPIO5

  temperature_sensor_dig: "0x6f0623b004a68a28"
  temperature_sensor_ssr: "0xca00000054519528"
  uptime_update_interval: 1min

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: ${device_comment}
  project: 
    name: timota.${device_name}
    version: ${device_version}

  devices:
    - id: light_strip
      name: ${device_friendly_name}

stairs_effects:
  id: stairs_effects_component
  led_map_id: map
  per_led_number_id: per_led_ms
  fade_steps_number_id: fade_steps_num
  row_threshold_number_id: row_trigger_threshold
  snake_switch_id: snake_mode
  wobble_switch_id: subtle_wobble_enable
  wobble_strength_number_id: subtle_hue_amp
  wobble_frequency_number_id: wobble_freq_deg
  easing_select_id: easing_mode
  shutdown_delay: 50ms

external_components:
  - source:
      type: local
      path: custom_components
 
esp32:
  board: esp32dev
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: ${ethernet_mdc_pin}
  mdio_pin: ${ethernet_mdio_pin}
  clk:
    pin: ${ethernet_clk_pin}
    mode: CLK_OUT
  phy_addr: ${ethernet_phy_addr}
  power_pin: ${ethernet_power_pin}

api:
  id: api_server
  reboot_timeout: ${system_reboot_timeout}
  encryption:
    key: ${system_api_key}

ota:
  - platform: esphome
    password: ${system_ota_password}

logger:
  level: ${system_log_level}

time:
  - platform: sntp
    id: sntp_time
    timezone: ${system_timezone}
    servers:
    - ${sntp_server}

web_server:
  include_internal: ${web_include_internal}
  local: ${web_local}
  version: 3

globals:
  - id: map
    type: std::vector<std::vector<int>>
    restore_value: no
    initial_value: ${light_led_map}

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

  - platform: safe_mode
    internal: false
    name: Safe mode
    entity_category: diagnostic
    disabled_by_default: True

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - platform: dallas_temp
    address: ${temperature_sensor_dig}
    id: dig_temperature
    name: "Temperature Dig Quad"
    unit_of_measurement: "°C"
    device_class: temperature
    update_interval: ${uptime_update_interval}
    device_id: light_strip

  - platform: dallas_temp
    address: ${temperature_sensor_ssr}
    id: ssr_temperature
    name: "Temperature SSR"
    unit_of_measurement: "°C"
    device_class: temperature
    update_interval: 60s
    device_id: light_strip

switch:

  - platform: gpio
    name: "Digital LED Power Relay"
    id: dig_power
    pin: GPIO15
    device_id: light_strip
    entity_category: config
    disabled_by_default: True

  - platform: factory_reset
    name: Restart with Factory Default Settings
    entity_category: diagnostic
    disabled_by_default: True


  - platform: template
    name: "Snake (zig-zag rows)"
    id: snake_mode
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    device_id: light_strip
    entity_category: config

  - platform: template
    name: "Subtle Wobble"
    id: subtle_wobble_enable
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:sine-wave
    device_id: light_strip
    entity_category: config

text_sensor:
  - platform: uptime
    update_interval: 1min
    name: Uptime
    format:
      separator: " "
    entity_category: diagnostic

number:
  - platform: template
    name: "Per-LED Time (ms)"
    id: per_led_ms
    min_value: 1
    max_value: 200
    step: 1
    initial_value: 18
    optimistic: true
    entity_category: config
    device_id: light_strip

  - platform: template
    name: "Fade Steps"
    id: fade_steps_num
    min_value: 1
    max_value: 64
    step: 1
    initial_value: 1
    optimistic: true
    entity_category: config
    device_id: light_strip

  - platform: template
    name: "Row Trigger Threshold"
    id: row_trigger_threshold
    min_value: 0.10
    max_value: 1.00
    step: 0.01
    initial_value: 0.55
    optimistic: true
    entity_category: config
    device_id: light_strip

  - platform: template
    name: "Wobble Strength (hue °)"
    id: subtle_hue_amp
    min_value: 0.0
    max_value: 15.0
    step: 0.5
    initial_value: 3.0
    optimistic: true
    entity_category: config
    device_id: light_strip

  - platform: template
    name: "Wobble Frequency (deg/s)"
    id: wobble_freq_deg
    min_value: 0.0
    max_value: 24.0
    step: 0.5
    initial_value: 12.0
    optimistic: true
    restore_value: true
    entity_category: config
    device_id: light_strip

# -------------------------
# SELECTS
# -------------------------
select:
  - platform: template
    name: "Easing"
    id: easing_mode
    optimistic: true
    options:
      - Linear
      - Cubic InOut
      - Quint InOut
    initial_option: Cubic InOut
    entity_category: config
    device_id: light_strip

light:

  - platform: esp32_rmt_led_strip
    id: light_dig
    name: Light
    rgb_order: RGB
    color_correct:
      - ${light_brightness_r}
      - ${light_brightness_g}
      - ${light_brightness_b}
    pin: GPIO16
    num_leds: ${light_num_leds}
    chipset: WS2811
    max_refresh_rate: 16ms
    use_psram: False
    restore_mode: ALWAYS_OFF
    device_id: light_strip
    default_transition_length: ${light_transition_length}
    on_turn_on: 
      then:
        - switch.turn_on: dig_power
    on_turn_off:
      then:
        - switch.turn_off: dig_power
    effects:
      - stairs_effects.fill_up:
          component_id: stairs_effects_component
      - stairs_effects.fill_down:
          component_id: stairs_effects_component
      - stairs_effects.off_up:
          component_id: stairs_effects_component
      - stairs_effects.off_down:
          component_id: stairs_effects_component
